preferred_syntax = :scss
http_path = '/'
css_dir = 'www/css/'
sass_dir = 'www/lib/ionic/scss'
images_dir = 'www/img'
javascripts_dir = 'www/js'
relative_assets = true
line_comments = true
# output_style = :compressed
